echo "curl \"https://ninja-weather.com/v1/weather?lat=\"9.876\"&lon=\"-5.678\"\" -X GET -o WAPI-LL-01.json"> WAPI-LL-01.sh
echo "curl \"https://ninja-weather.com/v1/weather?lat=\"-999\"&lon=\"999\"\" -X GET -o WAPI-LL-02.json"> WAPI-LL-02.sh
echo "curl \"https://ninja-weather.com/v1/weather?lon=\"-5.678\"\" -X GET -o WAPI-LL-03.json"> WAPI-LL-03.sh
echo "curl \"https://ninja-weather.com/v1/weather?lat=\"-5.678\"\" -X GET -o WAPI-LL-04.json"> WAPI-LL-04.sh
echo "curl \"https://ninja-weather.com/v1/weather?lat=\"0\"&lon=\"0\"\" -X GET -o WAPI-LL-05.json"> WAPI-LL-05.sh
echo "curl \"https://ninja-weather.com/v1/weather?lat=\"AbC\"&lon=\"dEf\"\" -X GET -o WAPI-LL-06.json"> WAPI-LL-06.sh
echo "curl \"https://ninja-weather.com/v1/weather?lat=\"9.876543210\"&lon=\"-5.678901234\"\" -X GET -o WAPI-LL-07.json"> WAPI-LL-07.sh
echo "curl \"https://ninja-weather.com/v1/weather?zip=\"90210\"\" -X GET -o WAPI-ZIP-01.json"> WAPI-ZIP-01.sh
echo "curl \"https://ninja-weather.com/v1/weather?zip=\"99999\"\" -X GET -o WAPI-ZIP-02.json"> WAPI-ZIP-02.sh
echo "curl \"https://ninja-weather.com/v1/weather?zip=\"110021\"\" -X GET -o WAPI-ZIP-03.json"> WAPI-ZIP-03.sh
echo "curl \"https://ninja-weather.com/v1/weather?zip=\"\"\" -X GET -o WAPI-ZIP-04.json"> WAPI-ZIP-04.sh
echo "curl \"https://ninja-weather.com/v1/weather?zip=\"E123A123\"\" -X GET -o WAPI-ZIP-05.json"> WAPI-ZIP-05.sh
echo "curl \"https://ninja-weather.com/v1/weather?city=\"Dallas\"\" -X GET -o WAPI-CIT-01.json"> WAPI-CIT-01.sh
echo "curl \"https://ninja-weather.com/v1/weather?state=\"NewYork\"\" -X GET -o WAPI-CIT-02.json"> WAPI-CIT-02.sh
echo "curl \"https://ninja-weather.com/v1/weather?state=\"NewYork\"&country=\"UnitedStates\"\" -X GET -o WAPI-CIT-03.json"> WAPI-CIT-03.sh
echo "curl \"https://ninja-weather.com/v1/weather?country=\"UnitedStates -X GET -o WAPI-CIT-04.json"> WAPI-CIT-04.sh
echo "curl \"https://ninja-weather.com/v1/weather?city=\"NY\"\" -X GET -o WAPI-CIT-05.json"> WAPI-CIT-05.sh
echo "curl \"https://ninja-weather.com/v1/weather?city=\"NY\"&state=\"NY\"\" -X GET -o WAPI-CIT-06.json"> WAPI-CIT-06.sh
echo "curl \"https://ninja-weather.com/v1/weather?city=\"NewYork&state=\"NY\"\" -X GET -o WAPI-CIT-07.json"> WAPI-CIT-07.sh
echo "curl \"https://ninja-weather.com/v1/weather?city=\"NewYork&state=\"NY&country=\"UnitedStates -X GET -o WAPI-CIT-08.json"> WAPI-CIT-08.sh
echo "curl \"https://ninja-weather.com/v1/weather?city=\"NewYork&country=\"US\"\" -X GET -o WAPI-CIT-09.json"> WAPI-CIT-09.sh
echo "curl \"https://ninja-weather.com/v1/weather?city=\"MexicoCity\"&state=\"MexicoCity\"&country=\"Mexico\"\" -X GET -o WAPI-CIT-10.json"> WAPI-CIT-10.sh